### ISSUE TITLE
rosserial_leonardo_cmake does not build on indigo

### ISSUE THREAD

**Issue by tfoote** [clearpathrobotics/rosserial_leonardo_cmake#2]
http://build.ros.org/view/Ibin_arm_uThf/job/Ibin_uT64__rosserial_leonardo_cmake__ubuntu_trusty_amd64__binary/31/console

```
# BEGIN SUBSECTION: build binarydeb
00:39:42 Package 'ros-indigo-rosserial-leonardo-cmake' version: 0.1.3-0trusty-20161125-003631-0800
00:39:44 Invoking 'apt-src build ros-indigo-rosserial-leonardo-cmake' in '/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3'
00:39:47 I: Building in /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3 ..
00:39:47 dpkg-buildpackage: source package ros-indigo-rosserial-leonardo-cmake
00:39:47 dpkg-buildpackage: source version 0.1.3-0trusty-20161125-003631-0800
00:39:47 dpkg-buildpackage: source distribution trusty
00:39:47 dpkg-buildpackage: source changed by Mike Purvis <mpurvis@clearpathrobotics.com>
00:39:47  dpkg-source --before-build ros-indigo-rosserial-leonardo-cmake-0.1.3
00:39:47 dpkg-buildpackage: host architecture amd64
00:39:47  fakeroot debian/rules clean
00:39:47 dh  clean
00:39:47 Unknown option: buildsystem
00:39:47 dh_testdir: warning: ignored unknown options in DH_OPTIONS
00:39:47    dh_testdir
00:39:47    dh_auto_clean
00:39:47    dh_clean
00:39:47 Unknown option: buildsystem
00:39:47 	rm -f debian/ros-indigo-rosserial-leonardo-cmake.substvars
00:39:47 dh_clean: warning: ignored unknown options in DH_OPTIONS
00:39:47  debian/rules build
00:39:47 	rm -f debian/ros-indigo-rosserial-leonardo-cmake.*.debhelper
00:39:47 	rm -rf debian/ros-indigo-rosserial-leonardo-cmake/
00:39:47 	rm -f debian/*.debhelper.log
00:39:47 	rm -f debian/files
00:39:47 	find .  \( \( -type f -a \
00:39:47 	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
00:39:47 		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
00:39:47 		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
00:39:47 		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
00:39:47 		\) -exec rm -f {} + \) -o \
00:39:47 		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
00:39:47 	rm -f *-stamp
00:39:47 dh  build
00:39:48    dh_testdir
00:39:48    debian/rules override_dh_auto_configure
00:39:48 make[1]: Entering directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3'
00:39:48 # In case we're installing to a non-standard location, look for a setup.sh
00:39:48 # in the install tree that was dropped by catkin, and source it.  It will
00:39:48 # set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
00:39:48 if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
00:39:48 	dh_auto_configure -- \
00:39:48 		-DCATKIN_BUILD_BINARY_PACKAGE="1" \
00:39:48 		-DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
00:39:48 		-DCMAKE_PREFIX_PATH="/opt/ros/indigo"
00:39:48 Unknown option: buildsystem
00:39:48 dh_testdir: warning: ignored unknown options in DH_OPTIONS
00:39:48 	mkdir -p obj-x86_64-linux-gnu
00:39:48 	cd obj-x86_64-linux-gnu
00:39:48 	cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo
00:39:48 -- The C compiler identification is GNU 4.8.4
00:39:48 -- The CXX compiler identification is GNU 4.8.4
00:39:48 -- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc
00:39:48 -- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc -- works
00:39:48 -- Detecting C compiler ABI info
00:39:48 -- Detecting C compiler ABI info - done
00:39:48 -- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++
00:39:48 -- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++ -- works
00:39:48 -- Detecting CXX compiler ABI info
00:39:48 -- Detecting CXX compiler ABI info - done
00:39:48 -- Using CATKIN_DEVEL_PREFIX: /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu/devel
00:39:48 -- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
00:39:48 -- This workspace overlays: /opt/ros/indigo
00:39:48 -- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
00:39:48 -- Using PYTHON_EXECUTABLE: /usr/bin/python
00:39:48 -- Using Debian Python package layout
00:39:48 -- Using empy: /usr/bin/empy
00:39:49 -- Using CATKIN_ENABLE_TESTING: ON
00:39:49 -- Skip enable_testing() when building binary package
00:39:49 -- Using CATKIN_TEST_RESULTS_DIR: /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu/test_results
00:39:49 -- Looking for include file pthread.h
00:39:49 -- Looking for include file pthread.h - found
00:39:49 -- Looking for pthread_create
00:39:49 -- Looking for pthread_create - not found
00:39:49 -- Looking for pthread_create in pthreads
00:39:49 -- Looking for pthread_create in pthreads - not found
00:39:49 -- Looking for pthread_create in pthread
00:39:49 -- Looking for pthread_create in pthread - found
00:39:49 -- Found Threads: TRUE  
00:39:49 -- Found gtest sources under '/usr/src/gtest': gtests will be built
00:39:49 -- Using Python nosetests: /usr/bin/nosetests-2.7
00:39:49 -- catkin 0.6.18
00:39:50 
00:39:50 gzip: stdin: unexpected end of file
00:39:50 tar: Child returned status 1
00:39:50 tar: Error is not recoverable: exiting now
00:39:50 -- Configuring done
00:39:50 -- Generating done
00:39:50 -- Build files have been written to: /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu
00:39:50 	cd /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3
00:39:50 make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3'
00:39:50    debian/rules override_dh_auto_build
00:39:50 make[1]: Entering directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3'
00:39:50 # In case we're installing to a non-standard location, look for a setup.sh
00:39:50 # in the install tree that was dropped by catkin, and source it.  It will
00:39:50 # set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
00:39:50 if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
00:39:50 	dh_auto_build
00:39:50 	cd obj-x86_64-linux-gnu
00:39:50 	make -j1
00:39:50 make[2]: Entering directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 /usr/bin/cmake -H/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3 -B/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu --check-build-system CMakeFiles/Makefile.cmake 0
00:39:50 /usr/bin/cmake -E cmake_progress_start /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu/CMakeFiles /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu/CMakeFiles/progress.marks
00:39:50 make -f CMakeFiles/Makefile2 all
00:39:50 make[3]: Entering directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 make -f CMakeFiles/rosserial_leonardo_cmake.dir/build.make CMakeFiles/rosserial_leonardo_cmake.dir/depend
00:39:50 make[4]: Entering directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 cd /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3 /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3 /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu /tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu/CMakeFiles/rosserial_leonardo_cmake.dir/DependInfo.cmake --color=
00:39:50 Scanning dependencies of target rosserial_leonardo_cmake
00:39:50 make[4]: Leaving directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 make -f CMakeFiles/rosserial_leonardo_cmake.dir/build.make CMakeFiles/rosserial_leonardo_cmake.dir/build
00:39:50 make[4]: Entering directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 make[4]: Leaving directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 make[3]: Leaving directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 make[2]: Leaving directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3/obj-x86_64-linux-gnu'
00:39:50 make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-rosserial-leonardo-cmake-0.1.3'
00:39:50 make[4]: *** No rule to make target `devel/share/rosserial_leonardo_cmake/arduino-1.0.5', needed by `CMakeFiles/rosserial_leonardo_cmake'.  Stop.
00:39:50 make[3]: *** [CMakeFiles/rosserial_leonardo_cmake.dir/all] Error 2
00:39:50 make[2]: *** [all] Error 2
00:39:50 dh_auto_build: make -j1 returned exit code 2
00:39:50 make[1]: *** [override_dh_auto_build] Error 2
00:39:50 make: *** [build] Error 2
00:39:50 dpkg-buildpackage: error: debian/rules build gave error exit status 2
00:39:50 E: Building failed
00:39:50 Traceback (most recent call last):
00:39:50   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
00:39:50     subprocess.check_call(cmd, cwd=source_dir)
00:39:50   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
00:39:50     raise CalledProcessError(retcode, cmd)
00:39:50 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-rosserial-leonardo-cmake']' returned non-zero exit status 1
00:39:50 
00:39:50 --------------------------------------------------------------------------------------------------
00:39:50 `apt-src build ros-indigo-rosserial-leonardo-cmake` failed.
00:39:50 This is usually because of an error building the package.
00:39:50 The traceback from this failure (just above) is printed for completeness, but you can ignore it.
00:39:50 You should look above `E: Building failed` in the build log for the actual cause of the failure.
00:39:50 --------------------------------------------------------------------------------------------------
00:39:50 
```

**Comment by tonybaltovski** [comment]
This was fixed awhile ago.
